/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package keyword_search_seedsprint;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "[SUCCESS] Program started";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        try 
        {
            // INFO: strict OOXML format is not supported for apache poi currently
            // file must be in other format such as xlsm
            // String fileDir = "src/main/resources/worddata1.xlsx";
            String fileDir = "src/main/resources/worddata1.xlsm";
            XlsxHandler.readXLSMFile(fileDir);
        } 
        catch (IOException e)
        {
            System.out.println("[FAIL] Catch Exception: " + e.getMessage());
        }
        
        DBHandler db = new DBHandler();
        db.init();

    }
}
